//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agravamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agravamento()
        {
            this.AgravamentoLinha = new HashSet<AgravamentoLinha>();
            this.AgravamentoApolice = new HashSet<AgravamentoApolice>();
            this.AgravamentoDespesa = new HashSet<AgravamentoDespesa>();
            this.AgravamentoPlano = new HashSet<AgravamentoPlano>();
            this.AreaGeograficaCobertura = new HashSet<AreaGeograficaCobertura>();
            this.CoeficientePremioAdesaoCobertura = new HashSet<CoeficientePremioAdesaoCobertura>();
            this.CoeficienteLimiteIndemnizacaoParto = new HashSet<CoeficienteLimiteIndemnizacaoParto>();
            this.CoeficientePremioAdesaoCobertura1 = new HashSet<CoeficientePremioAdesaoCobertura>();
            this.CondicaoAplicacaoAgravamento = new HashSet<CondicaoAplicacaoAgravamento>();
            this.LocaisCobertura = new HashSet<LocaisCobertura>();
            this.PerguntasPlano = new HashSet<PerguntasPlano>();
            this.TipoAdesao = new HashSet<TipoAdesao>();
            this.AgravamentoPessoa = new HashSet<AgravamentoPessoa>();
        }
    
        public string IdAgravamento { get; set; }
        public Nullable<double> TaxaAgravamento { get; set; }
        public Nullable<double> Valor { get; set; }
        public string TipoAgravamentoID { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public bool IsTaxa { get; set; }
        public Nullable<double> TaxaBase { get; set; }
        public Nullable<double> TaxaMin { get; set; }
        public Nullable<double> TaxaMax { get; set; }
        public Nullable<double> PremioBase { get; set; }
        public Nullable<double> PremioMax { get; set; }
        public Nullable<double> PremioMin { get; set; }
        public string CentroCustoId { get; set; }
        public string TipoRecebimentoId { get; set; }
        public string LocalAplicacaoId { get; set; }
        public string CodAgravamento { get; set; }
        public string TarifaId { get; set; }
        public Nullable<int> IdadeMin { get; set; }
        public Nullable<int> IdadeMax { get; set; }
        public string MoedaId { get; set; }
        public string TipoOperacaoId { get; set; }
        public Nullable<bool> IsParaIdoso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgravamentoLinha> AgravamentoLinha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgravamentoApolice> AgravamentoApolice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgravamentoDespesa> AgravamentoDespesa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgravamentoPlano> AgravamentoPlano { get; set; }
        public virtual CentroCusto CentroCusto { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual LocalAplicacaoPlano LocalAplicacaoPlano { get; set; }
        public virtual Moeda Moeda { get; set; }
        public virtual Tarifa Tarifa { get; set; }
        public virtual TipoAgravamento TipoAgravamento { get; set; }
        public virtual TipoOperacao TipoOperacao { get; set; }
        public virtual TipoRecebimento TipoRecebimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaGeograficaCobertura> AreaGeograficaCobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficientePremioAdesaoCobertura> CoeficientePremioAdesaoCobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficienteLimiteIndemnizacaoParto> CoeficienteLimiteIndemnizacaoParto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficientePremioAdesaoCobertura> CoeficientePremioAdesaoCobertura1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicaoAplicacaoAgravamento> CondicaoAplicacaoAgravamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocaisCobertura> LocaisCobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerguntasPlano> PerguntasPlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoAdesao> TipoAdesao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgravamentoPessoa> AgravamentoPessoa { get; set; }
    }
}
