//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aprovacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aprovacao()
        {
            this.ClassificacaoAprovacao = new HashSet<ClassificacaoAprovacao>();
        }
    
        public string IdAprovacao { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataAprovacao { get; set; }
        public Nullable<System.DateTime> DataSubscricao { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string AprovadorId { get; set; }
        public string TipoOperacaoId { get; set; }
        public Nullable<int> NumeroAprovacao { get; set; }
        public string PreponenteId { get; set; }
        public string EstadoId { get; set; }
        public string CodAprovacao { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
        public virtual OperacoesPagamento OperacoesPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassificacaoAprovacao> ClassificacaoAprovacao { get; set; }
    }
}
