//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Area()
        {
            this.Area1 = new HashSet<Area>();
            this.CentroCusto = new HashSet<CentroCusto>();
            this.CentroResponsabilidade = new HashSet<CentroResponsabilidade>();
            this.CompetenciaArea = new HashSet<CompetenciaArea>();
            this.DocumentoIdentificacao = new HashSet<DocumentoIdentificacao>();
            this.Funcionario = new HashSet<Funcionario>();
            this.GrupoArea = new HashSet<GrupoArea>();
            this.OperacoesCRUDPessoa = new HashSet<OperacoesCRUDPessoa>();
        }
    
        public string IdArea { get; set; }
        public string CodArea { get; set; }
        public string Ambito { get; set; }
        public string NomeArea { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public bool Contabiliza { get; set; }
        public string TipoAreaId { get; set; }
        public string AreaPrescendenteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area> Area1 { get; set; }
        public virtual Area Area2 { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual TipoArea TipoArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentroCusto> CentroCusto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentroResponsabilidade> CentroResponsabilidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetenciaArea> CompetenciaArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoIdentificacao> DocumentoIdentificacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionario> Funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoArea> GrupoArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacoesCRUDPessoa> OperacoesCRUDPessoa { get; set; }
    }
}
