//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artigos
    {
        public string IdArtigos { get; set; }
        public string Descricao { get; set; }
        public string CodArtigos { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public string UnidadeMedida { get; set; }
        public Nullable<double> PrecoUnitario { get; set; }
        public string MoedaId { get; set; }
        public string ClassificaoArtigosId { get; set; }
        public string NumeroONU { get; set; }
        public Nullable<double> ValorTributavelUnitario { get; set; }
        public string NumSerie { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
        public string ArmazemId { get; set; }
        public string AcordosId { get; set; }
    
        public virtual Acordos Acordos { get; set; }
        public virtual Armazem Armazem { get; set; }
        public virtual ClassificacaoArtigos ClassificacaoArtigos { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Moeda Moeda { get; set; }
    }
}
