//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoridadesContactadas
    {
        public string IdAutoridadeContactada { get; set; }
        public string NomeEntidadeID { get; set; }
        public Nullable<System.DateTime> DataContacto { get; set; }
        public string CorrespondenciaID { get; set; }
        public Nullable<System.DateTime> HoraContacto { get; set; }
        public string CodAutoridadesContactadasQuestionario { get; set; }
        public string SinistroID { get; set; }
        public string CodAutoridadesContactadas { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Sinistro Sinistro { get; set; }
        public virtual PostosAutoridade PostosAutoridade { get; set; }
    }
}
