//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class BemAfectado
    {
        public string IdBemAfectado { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<double> ValorUnitario { get; set; }
        public string MoedaID { get; set; }
        public string SinistroID { get; set; }
        public string Designacao { get; set; }
        public string ValorExtensao { get; set; }
        public Nullable<double> ValorCompreensao { get; set; }
        public string CaminhoFicheiro { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Moeda Moeda { get; set; }
        public virtual Sinistro Sinistro { get; set; }
    }
}
