//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficioCobertura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeneficioCobertura()
        {
            this.DescricaoBeneficioCobertura = new HashSet<DescricaoBeneficioCobertura>();
        }
    
        public string IdBeneficioCobertura { get; set; }
        public Nullable<double> ValorMonetarioCasoMorte { get; set; }
        public Nullable<double> ValorPremioInicialBeneficio { get; set; }
        public Nullable<double> ValorMensalMaximo { get; set; }
        public string CoberturaProdutoID { get; set; }
        public string CodBeneficioCobertura { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> NumOrdem { get; set; }
        public string Obs { get; set; }
    
        public virtual Cobertura Cobertura { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescricaoBeneficioCobertura> DescricaoBeneficioCobertura { get; set; }
    }
}
