//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bonus()
        {
            this.BonusTipoConta = new HashSet<BonusTipoConta>();
        }
    
        public string IdBonus { get; set; }
        public double TaxaBonus { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public string EstadoId { get; set; }
        public string PlanoProdutoID { get; set; }
        public Nullable<double> ValorMinPremioSimples { get; set; }
        public Nullable<double> ValorMaxPremioSimples { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<double> ValorMinBonus { get; set; }
        public Nullable<double> ValorMaxBonus { get; set; }
        public Nullable<bool> IsTaxa { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string MoedaID { get; set; }
        public string CanalId { get; set; }
        public string CentroCustoId { get; set; }
        public string TipoRecebimentoId { get; set; }
        public string ProdutorId { get; set; }
        public string CodBonus { get; set; }
        public string TipoOperacaoId { get; set; }
        public string TipoBonusId { get; set; }
        public Nullable<int> qtdAnos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusTipoConta> BonusTipoConta { get; set; }
    }
}
