//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAE()
        {
            this.Banco = new HashSet<Banco>();
            this.CaePessoa = new HashSet<CaePessoa>();
            this.CaePlano = new HashSet<CaePlano>();
            this.ContratoCae = new HashSet<ContratoCae>();
            this.Cotacao = new HashSet<Cotacao>();
            this.Empresa = new HashSet<Empresa>();
            this.EntidadeEmpregadora = new HashSet<EntidadeEmpregadora>();
            this.FinalidadeTratamento = new HashSet<FinalidadeTratamento>();
            this.Pessoa = new HashSet<Pessoa>();
            this.RendimentosPessoa = new HashSet<RendimentosPessoa>();
            this.SegmentoFranquia = new HashSet<SegmentoFranquia>();
            this.SegmentoProduto = new HashSet<SegmentoProduto>();
            this.SegmentoTipoCobertura = new HashSet<SegmentoTipoCobertura>();
            this.Simulacao = new HashSet<Simulacao>();
            this.SubSector = new HashSet<SubSector>();
        }
    
        public string IdCAE { get; set; }
        public string CodCAE { get; set; }
        public string Designacao { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string TituloCaeID { get; set; }
        public Nullable<double> TaxaComercial { get; set; }
        public string NivelRiscoID { get; set; }
        public bool IsTaxa { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string AutoridadeSupervisaoId { get; set; }
        public string ClassificacaoModalidadeCaeId { get; set; }
    
        public virtual AutoridadeSupervisao AutoridadeSupervisao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banco> Banco { get; set; }
        public virtual ClassificacaoModalidadeCae ClassificacaoModalidadeCae { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual NivelRisco NivelRisco { get; set; }
        public virtual SectorAtividadeEconomica SectorAtividadeEconomica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaePessoa> CaePessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaePlano> CaePlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoCae> ContratoCae { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotacao> Cotacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresa> Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadeEmpregadora> EntidadeEmpregadora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalidadeTratamento> FinalidadeTratamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendimentosPessoa> RendimentosPessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentoFranquia> SegmentoFranquia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentoProduto> SegmentoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentoTipoCobertura> SegmentoTipoCobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Simulacao> Simulacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubSector> SubSector { get; set; }
    }
}
