//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapitalSeguroAutomovel
    {
        public string IDCapitalAutomovel { get; set; }
        public string ClassificacaoAutomovelID { get; set; }
        public string MoedaID { get; set; }
        public Nullable<double> Capital { get; set; }
        public string EstadoID { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataActualizacao { get; set; }
        public string CodCapitalAutomovel { get; set; }
        public string PlanoProdutoId { get; set; }
    
        public virtual ClassificacaoAutomovel ClassificacaoAutomovel { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Moeda Moeda { get; set; }
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}
