//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaracteristicaClassificacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaracteristicaClassificacao()
        {
            this.CaracteristicaClassificacao1 = new HashSet<CaracteristicaClassificacao>();
            this.CaracteristicaObjecto = new HashSet<CaracteristicaObjecto>();
            this.ValorPadrao = new HashSet<ValorPadrao>();
        }
    
        public string IdCaracteristicaClassificacao { get; set; }
        public string Descricao { get; set; }
        public string ClassificacaoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
        public string SuperCaracteristicaId { get; set; }
    
        public virtual Classificacao Classificacao { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaracteristicaClassificacao> CaracteristicaClassificacao1 { get; set; }
        public virtual CaracteristicaClassificacao CaracteristicaClassificacao2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaracteristicaObjecto> CaracteristicaObjecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValorPadrao> ValorPadrao { get; set; }
    }
}
