//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cargo()
        {
            this.CargoPessoa = new HashSet<CargoPessoa>();
            this.EstatutoOrganicoDireccao = new HashSet<EstatutoOrganicoDireccao>();
            this.EstatutoOrganicoDepartamento = new HashSet<EstatutoOrganicoDepartamento>();
            this.EstatutoOrganicoSeccao = new HashSet<EstatutoOrganicoSeccao>();
            this.EstatutoOrganicoSector = new HashSet<EstatutoOrganicoSector>();
            this.FuncionarioCargo = new HashSet<FuncionarioCargo>();
            this.PessoaProfissao = new HashSet<PessoaProfissao>();
            this.Posicao = new HashSet<Posicao>();
            this.Seccao = new HashSet<Seccao>();
        }
    
        public string IdCargo { get; set; }
        public string CodCargo { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataActualizacao { get; set; }
        public string Designacao { get; set; }
        public Nullable<bool> CargoPublico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargoPessoa> CargoPessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstatutoOrganicoDireccao> EstatutoOrganicoDireccao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstatutoOrganicoDepartamento> EstatutoOrganicoDepartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstatutoOrganicoSeccao> EstatutoOrganicoSeccao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstatutoOrganicoSector> EstatutoOrganicoSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncionarioCargo> FuncionarioCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaProfissao> PessoaProfissao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posicao> Posicao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seccao> Seccao { get; set; }
    }
}
