//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartaConducao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CartaConducao()
        {
            this.Motorista = new HashSet<Motorista>();
        }
    
        public string IdCartaConducao { get; set; }
        public string NumLicenca { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<System.DateTime> DataPrimeiraEmissao { get; set; }
        public Nullable<System.DateTime> DataValidade { get; set; }
        public string CaminhoFicheiro { get; set; }
        public string CaminhoAssinatura { get; set; }
        public string RestricoesPessoaisCartaConducaoID { get; set; }
        public string RestricoesCategoriasCartaConducaoID { get; set; }
        public string RestricoesViaturaCartaConducaoID { get; set; }
        public string TipoCartaConducaoID { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EntidadeEmissoraID { get; set; }
        public string EstadoID { get; set; }
        public string CodCartaConducao { get; set; }
    
        public virtual EmissoraDocumentos EmissoraDocumentos { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual RestricoesPessoaisCartaConducao RestricoesPessoaisCartaConducao { get; set; }
        public virtual RestricoesCategoriasCartaConducao RestricoesCategoriasCartaConducao { get; set; }
        public virtual RestricoesViaturaCartaConducao RestricoesViaturaCartaConducao { get; set; }
        public virtual TipoCartaConducao TipoCartaConducao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Motorista> Motorista { get; set; }
    }
}
