//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Apolice = new HashSet<Apolice>();
            this.Movimento = new HashSet<Movimento>();
            this.PreferenciaUsuario = new HashSet<PreferenciaUsuario>();
        }
    
        public string IdCliente { get; set; }
        public Nullable<bool> Preferencias { get; set; }
        public string TipoClienteID { get; set; }
        public string FidelizacaoID { get; set; }
        public string PessoaID { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public long NumOrdemCliente { get; set; }
        public string CodCliente { get; set; }
        public string Conta { get; set; }
        public string TipoContaId { get; set; }
        public string SubClasseId { get; set; }
        public Nullable<bool> IndicadorAutofacturacao { get; set; }
        public string NomeClienteEmpresa { get; set; }
        public string TipoCarteiraClienteId { get; set; }
        public string CarteiraId { get; set; }
        public Nullable<System.DateTime> DataRelacaoFimCarteira { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apolice> Apolice { get; set; }
        public virtual Carteira Carteira { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Fidelizacao Fidelizacao { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual PlanoContas PlanoContas { get; set; }
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual TipoConta TipoConta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimento> Movimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreferenciaUsuario> PreferenciaUsuario { get; set; }
        public virtual TipoCarteiraCliente TipoCarteiraCliente { get; set; }
    }
}
