//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoberturaServico
    {
        public string IdCoberturaServico { get; set; }
        public string codCoberturaServico { get; set; }
        public string CoberturaId { get; set; }
        public string ServicoId { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        public virtual Cobertura Cobertura { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Servico Servico { get; set; }
    }
}
