//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColaboradoresGoi
    {
        public string IdColaboradoresGoi { get; set; }
        public string ColaboradorId { get; set; }
        public Nullable<double> ValorObjectivo { get; set; }
        public Nullable<double> ValorReal { get; set; }
        public Nullable<double> Ponderacao { get; set; }
        public string ObjectivosSeccaoId { get; set; }
        public Nullable<System.DateTime> Datacriacao { get; set; }
        public Nullable<System.DateTime> DataActualizao { get; set; }
        public string EstadoId { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ObjectivosSeccao ObjectivosSeccao { get; set; }
    }
}
