//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comite
    {
        public string IdComite { get; set; }
        public string Designacao { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string SubContaId { get; set; }
        public string EstadoId { get; set; }
        public string EmpresaId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual PlanoContas PlanoContas { get; set; }
    }
}
