//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComparticipacaoDespesa
    {
        public string IdComparticipacaoDespesa { get; set; }
        public string DespesaId { get; set; }
        public string ComparticipacaoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        public virtual Comparticipacao Comparticipacao { get; set; }
        public virtual Comparticipacao Comparticipacao1 { get; set; }
        public virtual Despesa Despesa { get; set; }
    }
}
