//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComparticipacaoServico
    {
        public string IdComparticipacaoServico { get; set; }
        public string ServicoId { get; set; }
        public Nullable<double> TaxaForaRede { get; set; }
        public Nullable<double> TaxaDentroRede { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        public virtual Servico Servico { get; set; }
    }
}
