//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetenciaArea
    {
        public string IdCompetenciaArea { get; set; }
        public int NumCompetencia { get; set; }
        public string Designacao { get; set; }
        public string AreaID { get; set; }
        public string EstadoID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
