//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condicoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Condicoes()
        {
            this.Capitulo = new HashSet<Capitulo>();
            this.CondicoesApolice = new HashSet<CondicoesApolice>();
            this.CondicoesReSeguro = new HashSet<CondicoesReSeguro>();
            this.CondicoesCoSeguro = new HashSet<CondicoesCoSeguro>();
        }
    
        public string IdCondicao { get; set; }
        public string Designacao { get; set; }
        public string CaminhoFicheiro { get; set; }
        public string TipoCondicoesID { get; set; }
        public string CodCondicoes { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Capitulo> Capitulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicoesApolice> CondicoesApolice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicoesReSeguro> CondicoesReSeguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicoesCoSeguro> CondicoesCoSeguro { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual TipoCondicoes TipoCondicoes { get; set; }
    }
}
