//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContaTerceiros
    {
        public string IdContaTerceiros { get; set; }
        public Nullable<System.DateTime> DataHoraMovimento { get; set; }
        public string DescricaoMovimento { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<System.DateTime> DataValor { get; set; }
        public double Valor { get; set; }
        public string CodEstado { get; set; }
        public string CodContaFinanceira { get; set; }
        public string CodTransacao { get; set; }
        public string NumeroDocumentoInterno { get; set; }
        public string CodCaixa { get; set; }
        public string CodEndereco { get; set; }
        public string CodTipoOperacao { get; set; }
        public Nullable<bool> IsPago { get; set; }
        public Nullable<bool> Contabliza { get; set; }
        public string CodFavorecido { get; set; }
        public string CodOutraMoeda { get; set; }
        public string CodCentroResponsabilidade { get; set; }
        public string CodCentroCusto { get; set; }
        public string Referencia { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public Nullable<System.DateTime> DataProgramada { get; set; }
        public Nullable<int> DocumentoParcelado { get; set; }
        public string Identificador { get; set; }
        public string NumeroDocumentoExterno { get; set; }
        public string CodEmpresa { get; set; }
        public string CodTipoPagamento { get; set; }
        public Nullable<double> ValorOutraMoeda { get; set; }
        public string CodFraccionamento { get; set; }
        public string CodOperacoesPagamento { get; set; }
        public string CodMoeda { get; set; }
        public string CodNaturezaMovimento { get; set; }
        public string CodConta { get; set; }
        public string CodOperacao { get; set; }
        public string ContaFinanceiraId { get; set; }
        public string CodFuncionario { get; set; }
        public string CodExercicio { get; set; }
        public string CodTipoDocumentos { get; set; }
    }
}
