//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.CanalContratos = new HashSet<CanalContratos>();
            this.CoberturaResseguro = new HashSet<CoberturaResseguro>();
            this.ContactoPessoaParteContrato = new HashSet<ContactoPessoaParteContrato>();
            this.ContratoApolice = new HashSet<ContratoApolice>();
            this.ContratoAgenda = new HashSet<ContratoAgenda>();
            this.ContratoCae = new HashSet<ContratoCae>();
            this.ContratoComissionamento = new HashSet<ContratoComissionamento>();
            this.ContratoFormaPagamento = new HashSet<ContratoFormaPagamento>();
            this.ContratoFidelizazao = new HashSet<ContratoFidelizazao>();
            this.ContratoMoeda = new HashSet<ContratoMoeda>();
            this.ContratoNota = new HashSet<ContratoNota>();
            this.ContratoPlano = new HashSet<ContratoPlano>();
            this.ContratoResseguro = new HashSet<ContratoResseguro>();
            this.ContratoSegmentos = new HashSet<ContratoSegmentos>();
            this.ContratoTipoPessoa = new HashSet<ContratoTipoPessoa>();
            this.ContratoTarefa = new HashSet<ContratoTarefa>();
            this.Cotacao = new HashSet<Cotacao>();
            this.DespesaContrato = new HashSet<DespesaContrato>();
            this.EncargosContrato = new HashSet<EncargosContrato>();
            this.FidelizacaoContrato = new HashSet<FidelizacaoContrato>();
            this.ImpostoContrato = new HashSet<ImpostoContrato>();
            this.IndeminizacaoResseguro = new HashSet<IndeminizacaoResseguro>();
            this.InformacaoBancariaContrato = new HashSet<InformacaoBancariaContrato>();
            this.LimiteComissionamentoProdutor = new HashSet<LimiteComissionamentoProdutor>();
            this.PaisContrato = new HashSet<PaisContrato>();
            this.PartesContrato = new HashSet<PartesContrato>();
            this.PessoaContactoContratado = new HashSet<PessoaContactoContratado>();
            this.PessoaContactoContratante = new HashSet<PessoaContactoContratante>();
            this.PessoaParteContrato = new HashSet<PessoaParteContrato>();
            this.PlanoProdutoContrato = new HashSet<PlanoProdutoContrato>();
            this.ProvinciaContrato = new HashSet<ProvinciaContrato>();
            this.Resseguro = new HashSet<Resseguro>();
            this.SectorAtividadeEconomicaContrato = new HashSet<SectorAtividadeEconomicaContrato>();
            this.ServicoContrato = new HashSet<ServicoContrato>();
            this.TaxaLimiteRapelContrato = new HashSet<TaxaLimiteRapelContrato>();
            this.TipoComissionamentoResseguro = new HashSet<TipoComissionamentoResseguro>();
            this.TipoSegmentoContrato = new HashSet<TipoSegmentoContrato>();
        }
    
        public string IdContrato { get; set; }
        public long NumeroContrato { get; set; }
        public string Referencia { get; set; }
        public string ContratanteId { get; set; }
        public System.DateTime DataAssinatura { get; set; }
        public System.DateTime DataVencimento { get; set; }
        public double Valor { get; set; }
        public Nullable<long> NumeroPrestacoesPagas { get; set; }
        public Nullable<long> NumeroPrestacoesAPagar { get; set; }
        public Nullable<double> TotalValorPago { get; set; }
        public Nullable<double> TotalValorAPagar { get; set; }
        public string EstadoId { get; set; }
        public string CodContrato { get; set; }
        public string EnderecoId { get; set; }
        public string MoradaCobrancaContratoId { get; set; }
        public string MoradaAssinaturaId { get; set; }
        public string TipoPagamentoId { get; set; }
        public string ContaFinanceiraId { get; set; }
        public string TipoContratoId { get; set; }
        public string Designacao { get; set; }
        public string DuracaoTipoContratoId { get; set; }
        public Nullable<int> NumDias { get; set; }
        public string CentroCustoId { get; set; }
        public string CentroResponsabilidadeId { get; set; }
        public Nullable<double> Cedencia { get; set; }
        public Nullable<double> Retencao { get; set; }
        public string FraccionamentoId { get; set; }
        public string MoedaId { get; set; }
        public string FormaPagamentoId { get; set; }
        public string TipoOperacaoId { get; set; }
        public Nullable<bool> FazRetencaoNaFonte { get; set; }
        public Nullable<System.DateTime> DiaPagamento { get; set; }
        public string Ano { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public Nullable<System.DateTime> DataRenovacao { get; set; }
        public string PrazoAlteracao { get; set; }
        public string PrazoPreAviso { get; set; }
        public string FormaFacturacao { get; set; }
        public string MoradaCobranca { get; set; }
        public string ContratadoId { get; set; }
        public string ProdutorId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string ComissionamentoId { get; set; }
        public Nullable<int> NumInterveniente { get; set; }
        public string EmpresaContratanteId { get; set; }
        public string LinhaProdutoId { get; set; }
        public string FormaContratacaoId { get; set; }
        public string FormaContratacaoTipoContratoId { get; set; }
        public string Notas { get; set; }
        public string AgenciaID { get; set; }
        public string UsuarioID { get; set; }
        public string CanalID { get; set; }
        public string ClassificacaoFormaTipoResseguroId { get; set; }
        public string ApoliceId { get; set; }
        public Nullable<double> LimiteResseguro { get; set; }
        public string FormaResseguroCoberturaId { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        public virtual Apolice Apolice { get; set; }
        public virtual Canal Canal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanalContratos> CanalContratos { get; set; }
        public virtual CentroCusto CentroCusto { get; set; }
        public virtual CentroResponsabilidade CentroResponsabilidade { get; set; }
        public virtual ClassificacaoFormaTipoResseguro ClassificacaoFormaTipoResseguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoberturaResseguro> CoberturaResseguro { get; set; }
        public virtual Comissionamento Comissionamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactoPessoaParteContrato> ContactoPessoaParteContrato { get; set; }
        public virtual ContaFinanceira ContaFinanceira { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual DuracaoTipoContrato DuracaoTipoContrato { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Endereco Endereco { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual FormaContratacao FormaContratacao { get; set; }
        public virtual FormaContratacaoTipoContrato FormaContratacaoTipoContrato { get; set; }
        public virtual FormaPagamento FormaPagamento { get; set; }
        public virtual FormaResseguroCobertura FormaResseguroCobertura { get; set; }
        public virtual Fraccionamento Fraccionamento { get; set; }
        public virtual LinhaProduto LinhaProduto { get; set; }
        public virtual Moeda Moeda { get; set; }
        public virtual Endereco Endereco1 { get; set; }
        public virtual Endereco Endereco2 { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
        public virtual TipoOperacao TipoOperacao { get; set; }
        public virtual TipoPagamento TipoPagamento { get; set; }
        public virtual Pessoa Pessoa2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoApolice> ContratoApolice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoAgenda> ContratoAgenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoCae> ContratoCae { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoComissionamento> ContratoComissionamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoFormaPagamento> ContratoFormaPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoFidelizazao> ContratoFidelizazao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoMoeda> ContratoMoeda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoNota> ContratoNota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoPlano> ContratoPlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoResseguro> ContratoResseguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoSegmentos> ContratoSegmentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoTipoPessoa> ContratoTipoPessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoTarefa> ContratoTarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotacao> Cotacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespesaContrato> DespesaContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncargosContrato> EncargosContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FidelizacaoContrato> FidelizacaoContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpostoContrato> ImpostoContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndeminizacaoResseguro> IndeminizacaoResseguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformacaoBancariaContrato> InformacaoBancariaContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LimiteComissionamentoProdutor> LimiteComissionamentoProdutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaisContrato> PaisContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartesContrato> PartesContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaContactoContratado> PessoaContactoContratado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaContactoContratante> PessoaContactoContratante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaParteContrato> PessoaParteContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanoProdutoContrato> PlanoProdutoContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvinciaContrato> ProvinciaContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resseguro> Resseguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectorAtividadeEconomicaContrato> SectorAtividadeEconomicaContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicoContrato> ServicoContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxaLimiteRapelContrato> TaxaLimiteRapelContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoComissionamentoResseguro> TipoComissionamentoResseguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoSegmentoContrato> TipoSegmentoContrato { get; set; }
        public virtual Pessoa Pessoa3 { get; set; }
    }
}
