//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoPessoaParteContrato
    {
        public string IdPessoaParteContrato { get; set; }
        public string PessoaParteContratoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string PessoaContactoId { get; set; }
        public string PapelId { get; set; }
        public string ContaFinanceiraId { get; set; }
        public string ContratoId { get; set; }
    
        public virtual ContaFinanceira ContaFinanceira { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Papel Papel { get; set; }
        public virtual PessoaParteContrato PessoaParteContrato { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
