//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoEmpresa
    {
        public string IdContactoPessoa { get; set; }
        public Nullable<bool> Principal { get; set; }
        public string EmpresaId { get; set; }
        public string ContactoID { get; set; }
        public string EstadoID { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
