//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriteriosSeguranca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CriteriosSeguranca()
        {
            this.CondicoesVisibilidade1 = new HashSet<CondicoesVisibilidade>();
        }
    
        public string IdCriteriosSeguranca { get; set; }
        public Nullable<double> VelocidadeTrafego { get; set; }
        public Nullable<double> LimiteVelocidade { get; set; }
        public Nullable<bool> CondicoesVisibilidade { get; set; }
        public string InclinacaoLongitudinalId { get; set; }
        public Nullable<double> InclinacaoTransversal { get; set; }
        public Nullable<bool> ReducaoVelocidade { get; set; }
        public Nullable<bool> Hidroplanagem { get; set; }
        public string SinalizacaoAplicavelId { get; set; }
        public string ZonaEmbateAparente { get; set; }
        public string CodCriteriosSeguranca { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicoesVisibilidade> CondicoesVisibilidade1 { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual InclinacaoLongitudinal InclinacaoLongitudinal { get; set; }
        public virtual SinalizacaoAplicavel SinalizacaoAplicavel { get; set; }
    }
}
