//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriterioComissionamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CriterioComissionamento()
        {
            this.CanalComissionamento = new HashSet<CanalComissionamento>();
            this.FidelizacaoComissionamento = new HashSet<FidelizacaoComissionamento>();
            this.ProvinciaComissionamento = new HashSet<ProvinciaComissionamento>();
            this.TipoSegmentoComissionamento = new HashSet<TipoSegmentoComissionamento>();
        }
    
        public string IdCriterioComissionamento { get; set; }
        public string ComissionamentoId { get; set; }
        public string CanalId { get; set; }
        public string SegmentoPlanoId { get; set; }
        public string LimiteComissionamentoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
        public string CodCriterioComissionamento { get; set; }
    
        public virtual Canal Canal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanalComissionamento> CanalComissionamento { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual TipoSegmentoPlano TipoSegmentoPlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FidelizacaoComissionamento> FidelizacaoComissionamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvinciaComissionamento> ProvinciaComissionamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoSegmentoComissionamento> TipoSegmentoComissionamento { get; set; }
    }
}
