//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosPessoaisTratados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DadosPessoaisTratados()
        {
            this.DadosPessoaisTratadosTratamentoDados = new HashSet<DadosPessoaisTratadosTratamentoDados>();
            this.DadosPessoaisTratadosITDP = new HashSet<DadosPessoaisTratadosITDP>();
        }
    
        public string IdDadosPessoaisTratados { get; set; }
        public string Designacao { get; set; }
        public string CodDadosPessoaisTratados { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DadosPessoaisTratadosTratamentoDados> DadosPessoaisTratadosTratamentoDados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DadosPessoaisTratadosITDP> DadosPessoaisTratadosITDP { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
