//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desconto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Desconto()
        {
            this.AreaGeograficaCobertura = new HashSet<AreaGeograficaCobertura>();
            this.CanalDesconto = new HashSet<CanalDesconto>();
            this.ClassificacaoAutomovelDesconto = new HashSet<ClassificacaoAutomovelDesconto>();
            this.CoeficienteLimiteIndemnizacaoParto = new HashSet<CoeficienteLimiteIndemnizacaoParto>();
            this.DescontoApoliceGrupo = new HashSet<DescontoApoliceGrupo>();
            this.DescontoLinha = new HashSet<DescontoLinha>();
            this.DescontoPlanoProduto = new HashSet<DescontoPlanoProduto>();
            this.DescontoProvincia = new HashSet<DescontoProvincia>();
            this.DescontoProduto = new HashSet<DescontoProduto>();
            this.DescontoPlano = new HashSet<DescontoPlano>();
            this.DescontoPessoa = new HashSet<DescontoPessoa>();
            this.DescontoSectorActividade = new HashSet<DescontoSectorActividade>();
            this.DescontoSeleccionado = new HashSet<DescontoSeleccionado>();
            this.DescontoTipoConta = new HashSet<DescontoTipoConta>();
            this.FormaContratacaoDesconto = new HashSet<FormaContratacaoDesconto>();
            this.FormaContratacao = new HashSet<FormaContratacao>();
            this.LocaisDesconto = new HashSet<LocaisDesconto>();
            this.MembroAssegurado = new HashSet<MembroAssegurado>();
            this.PaisesPlanoProduto = new HashSet<PaisesPlanoProduto>();
            this.PapelDesconto = new HashSet<PapelDesconto>();
            this.ProvinciaPlano = new HashSet<ProvinciaPlano>();
        }
    
        public string IdDesconto { get; set; }
        public Nullable<double> Taxa { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public string EstadoId { get; set; }
        public string TipoDescontoID { get; set; }
        public string CodDesconto { get; set; }
        public Nullable<double> ValorMinPremioSimples { get; set; }
        public Nullable<double> ValorMaxPremioSimples { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<double> ValorMinDesconto { get; set; }
        public Nullable<double> ValorMaxDesconto { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string MoedaID { get; set; }
        public string TipoTarifaId { get; set; }
        public string CentroCustoId { get; set; }
        public string TipoPagamentoId { get; set; }
        public string LocalAplicacaoId { get; set; }
        public Nullable<bool> IsTaxa { get; set; }
        public string Nota { get; set; }
        public string PlanoProdutoId { get; set; }
        public string ProdutorId { get; set; }
        public string TipoOperacaoId { get; set; }
        public Nullable<int> NumMinPessoa { get; set; }
        public Nullable<int> NumMaxPessoa { get; set; }
        public Nullable<double> TaxaMin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaGeograficaCobertura> AreaGeograficaCobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanalDesconto> CanalDesconto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassificacaoAutomovelDesconto> ClassificacaoAutomovelDesconto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficienteLimiteIndemnizacaoParto> CoeficienteLimiteIndemnizacaoParto { get; set; }
        public virtual TipoOperacao TipoOperacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoApoliceGrupo> DescontoApoliceGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoLinha> DescontoLinha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoPlanoProduto> DescontoPlanoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoProvincia> DescontoProvincia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoProduto> DescontoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoPlano> DescontoPlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoPessoa> DescontoPessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoSectorActividade> DescontoSectorActividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoSeleccionado> DescontoSeleccionado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoTipoConta> DescontoTipoConta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormaContratacaoDesconto> FormaContratacaoDesconto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormaContratacao> FormaContratacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocaisDesconto> LocaisDesconto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembroAssegurado> MembroAssegurado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaisesPlanoProduto> PaisesPlanoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PapelDesconto> PapelDesconto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvinciaPlano> ProvinciaPlano { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}
