//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Despesa()
        {
            this.AgravamentoDespesa = new HashSet<AgravamentoDespesa>();
            this.ComparticipacaoCobertura = new HashSet<ComparticipacaoCobertura>();
            this.ComparticipacaoDespesa = new HashSet<ComparticipacaoDespesa>();
            this.DespesaApolice = new HashSet<DespesaApolice>();
            this.DespesaContrato = new HashSet<DespesaContrato>();
            this.DespesaLinha = new HashSet<DespesaLinha>();
            this.DespesaPlano = new HashSet<DespesaPlano>();
            this.DespesasCobertura = new HashSet<DespesasCobertura>();
            this.DespesaSeleccionada = new HashSet<DespesaSeleccionada>();
            this.DespesasTipoConta = new HashSet<DespesasTipoConta>();
        }
    
        public string IdDespesa { get; set; }
        public Nullable<double> ValorMin { get; set; }
        public string TipoDespesaID { get; set; }
        public string CodDespesa { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<double> ValorMax { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public bool IsTaxa { get; set; }
        public string MoedaID { get; set; }
        public string CanalId { get; set; }
        public string CentroCustoId { get; set; }
        public string TipoRecebimentoId { get; set; }
        public string LocalAplicacaoId { get; set; }
        public string ProdutorId { get; set; }
        public string CoberturaId { get; set; }
        public string TipoOperacaoId { get; set; }
        public string Designacao { get; set; }
        public Nullable<double> Taxa { get; set; }
        public string NivelRiscoId { get; set; }
        public string TipoConta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgravamentoDespesa> AgravamentoDespesa { get; set; }
        public virtual Canal Canal { get; set; }
        public virtual CentroCusto CentroCusto { get; set; }
        public virtual Cobertura Cobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComparticipacaoCobertura> ComparticipacaoCobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComparticipacaoDespesa> ComparticipacaoDespesa { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual LocalAplicacaoPlano LocalAplicacaoPlano { get; set; }
        public virtual Moeda Moeda { get; set; }
        public virtual NivelRisco NivelRisco { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual TipoConta TipoConta1 { get; set; }
        public virtual TipoDespesa TipoDespesa { get; set; }
        public virtual TipoOperacao TipoOperacao { get; set; }
        public virtual TipoRecebimento TipoRecebimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespesaApolice> DespesaApolice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespesaContrato> DespesaContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespesaLinha> DespesaLinha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespesaPlano> DespesaPlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespesasCobertura> DespesasCobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespesaSeleccionada> DespesaSeleccionada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespesasTipoConta> DespesasTipoConta { get; set; }
    }
}
