//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestaquesPagina
    {
        public string IdDestaquesPagina { get; set; }
        public string Titulo { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataActualizacao { get; set; }
        public string InformacaoBase { get; set; }
        public string CorTituloId { get; set; }
        public string CorInformacaoBaseId { get; set; }
        public string CaminhoWeb { get; set; }
        public string CaminhoImagem { get; set; }
    
        public virtual Cor Cor { get; set; }
        public virtual Cor Cor1 { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
