//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosLinhaEstadoAtualDocumento
    {
        public string IdDocumentosLinhaEstadoAtualDocumento { get; set; }
        public string DocumentosLinhaId { get; set; }
        public string EstadoAtualDocumentoId { get; set; }
        public string CodDocumentosLinhaEstadoAtualDocumento { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
        public string MotivoAlteracaoEstado { get; set; }
    
        public virtual DocumentosLinha DocumentosLinha { get; set; }
        public virtual EstadoAtualDocumento EstadoAtualDocumento { get; set; }
    }
}
