//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultativoResseguro
    {
        public string IdFacultativoResseguro { get; set; }
        public Nullable<double> Cedencia { get; set; }
        public string ComissaoId { get; set; }
        public string SinistroId { get; set; }
        public string MoedaId { get; set; }
        public Nullable<double> ValorLiquido { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
        public string EntidadeId { get; set; }
    
        public virtual Comissao Comissao { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Moeda Moeda { get; set; }
        public virtual Sinistro Sinistro { get; set; }
    }
}
