//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaContratacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormaContratacao()
        {
            this.Contrato = new HashSet<Contrato>();
            this.Cotacao = new HashSet<Cotacao>();
            this.FormaContratacaoDesconto = new HashSet<FormaContratacaoDesconto>();
            this.FormaContratacaoTipoContrato = new HashSet<FormaContratacaoTipoContrato>();
            this.FormaContratacaoPlano = new HashSet<FormaContratacaoPlano>();
            this.GrupoEtario = new HashSet<GrupoEtario>();
            this.NumeroPessoasAbrangivel = new HashSet<NumeroPessoasAbrangivel>();
            this.TipoAdesao = new HashSet<TipoAdesao>();
            this.TipoClassificacaoGrupo = new HashSet<TipoClassificacaoGrupo>();
        }
    
        public string IdFormaContratacao { get; set; }
        public string Designacao { get; set; }
        public string CodFormaContratacao { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string CaminhoIcone { get; set; }
        public string DescontoId { get; set; }
        public string TipoPessoaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotacao> Cotacao { get; set; }
        public virtual Desconto Desconto { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormaContratacaoDesconto> FormaContratacaoDesconto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormaContratacaoTipoContrato> FormaContratacaoTipoContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormaContratacaoPlano> FormaContratacaoPlano { get; set; }
        public virtual TipoPessoa TipoPessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoEtario> GrupoEtario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumeroPessoasAbrangivel> NumeroPessoasAbrangivel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoAdesao> TipoAdesao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoClassificacaoGrupo> TipoClassificacaoGrupo { get; set; }
    }
}
