//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class FraccionamentoValores
    {
        public string IdFraccionamentoValores { get; set; }
        public string CotacaoId { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Impostos { get; set; }
        public Nullable<double> Despesas { get; set; }
        public Nullable<double> Fga { get; set; }
        public Nullable<double> CapitalSeguro { get; set; }
        public Nullable<double> PremioCobrado { get; set; }
        public Nullable<double> PremioTotal { get; set; }
        public Nullable<double> Arseg { get; set; }
        public Nullable<double> PremioComercial { get; set; }
        public Nullable<double> JurosFraccionamento { get; set; }
        public Nullable<double> EncargosAdministrativos { get; set; }
        public Nullable<double> PremioSimples { get; set; }
        public string FraccionamentoId { get; set; }
        public string PremioBase { get; set; }
        public string SinistroEsperado { get; set; }
        public string PremioRisco { get; set; }
        public string Taxa { get; set; }
        public string EncargosAdminstrativos { get; set; }
        public string Encargos { get; set; }
        public string PremioBruto { get; set; }
        public string Descontos { get; set; }
        public string DescontosPorIdade { get; set; }
        public string Ofertas { get; set; }
        public string Comissoes { get; set; }
        public string Agravamentos { get; set; }
        public string AgravamentosPorIdade { get; set; }
        public string ValorCobertura { get; set; }
        public Nullable<double> FraccionamentoMensal { get; set; }
        public Nullable<double> FraccionamentoTrimestral { get; set; }
        public Nullable<double> FraccionamentoSemestral { get; set; }
        public Nullable<double> FraccionamentoAnual { get; set; }
    
        public virtual Cotacao Cotacao { get; set; }
        public virtual Fraccionamento Fraccionamento { get; set; }
    }
}
