//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncaoDependente
    {
        public string IdFuncaoDependente { get; set; }
        public string FuncaoDependenteID { get; set; }
        public string FuncaoMaeId { get; set; }
    
        public virtual Funcao Funcao { get; set; }
        public virtual Funcao Funcao1 { get; set; }
    }
}
