//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glossario
    {
        public string IdGlossario { get; set; }
        public string ProcessoElemento { get; set; }
        public string HierarquiaID { get; set; }
        public string ElementoProcesso { get; set; }
        public string Definicao { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string CodGlossario { get; set; }
        public string ProdutoID { get; set; }
        public string LinhaProdutoID { get; set; }
        public string CategoriaGlossarioID { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public Nullable<int> InApolice { get; set; }
        public string Url { get; set; }
    
        public virtual CategoriaGlossario CategoriaGlossario { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual LinhaProduto LinhaProduto { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
