//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoObjectivos
    {
        public string IdGrupoObjectivos { get; set; }
        public string Designacao { get; set; }
        public Nullable<System.DateTime> Datacriacao { get; set; }
        public Nullable<System.DateTime> DataActualizao { get; set; }
        public string EstadoId { get; set; }
    
        public virtual Estado Estado { get; set; }
    }
}
