//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoAgravamento
    {
        public string IdHistoricoAgravamento { get; set; }
        public string IdAgravamento { get; set; }
        public Nullable<double> TaxaAgravamento { get; set; }
        public Nullable<double> ValorAgravamento { get; set; }
        public string TipoAgravamentoID { get; set; }
        public string EstadoId { get; set; }
        public string PlanoProdutoID { get; set; }
        public string LinhaProdutoID { get; set; }
        public string ProdutoID { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<bool> IsTaxa { get; set; }
        public string PrecarioProdutoID { get; set; }
    }
}
