//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoFranquia
    {
        public string IdHistoricoFranquia { get; set; }
        public string IdFranquia { get; set; }
        public Nullable<double> TaxaMinFranquia { get; set; }
        public Nullable<double> ValorFranquiaMin { get; set; }
        public Nullable<double> ValorFranquiaMax { get; set; }
        public string TipoFranquiaID { get; set; }
        public string CategoriaFranquiaID { get; set; }
        public string EstadoId { get; set; }
        public string PlanoProdutoID { get; set; }
        public string Designacao { get; set; }
        public string CodFranquia { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<double> TaxaMaxFranquia { get; set; }
        public Nullable<double> Desconto { get; set; }
        public Nullable<bool> IsTaxa { get; set; }
        public string CoberturaProdutoID { get; set; }
        public string CoberturasComplementaresID { get; set; }
        public Nullable<int> DiaMin { get; set; }
        public Nullable<int> DiaMax { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string ProdutoID { get; set; }
        public string LinhaProdutoID { get; set; }
    }
}
