//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indeminizacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indeminizacao()
        {
            this.IndeminizacaoResseguro = new HashSet<IndeminizacaoResseguro>();
        }
    
        public string idIndeminizacao { get; set; }
        public string SinistroId { get; set; }
        public string CoberturaSelecionadaId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<bool> isResseguro { get; set; }
    
        public virtual CoberturaSelecionada CoberturaSelecionada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndeminizacaoResseguro> IndeminizacaoResseguro { get; set; }
        public virtual Sinistro Sinistro { get; set; }
    }
}
