//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacaoAdicional
    {
        public string IdInformacaoAdicional { get; set; }
        public string CodInformacaoAdicional { get; set; }
        public string DescricaoInformacaoAdicional { get; set; }
        public Nullable<double> PercentagemNivelFincanceiro { get; set; }
        public Nullable<double> MontanteNivelFinanceiro { get; set; }
        public bool CoberturaDanosAcidentaisNecessaria { get; set; }
        public string IdentificadorContrato { get; set; }
        public Nullable<double> ValorClassificacao { get; set; }
        public Nullable<bool> PagadorInteresseAdicional { get; set; }
        public string CodigoFrequenciaFactura { get; set; }
        public string CodigoFrequenciaCopiaCertificado { get; set; }
        public string DescricaoFrequenciaCopiaCertificado { get; set; }
        public Nullable<System.DateTime> DataHoraProximaRequisicaoCertificado { get; set; }
        public Nullable<System.DateTime> DataHoraUltimaEmissaoCertificado { get; set; }
        public Nullable<System.DateTime> DataHoraProximaRequisicaoApolice { get; set; }
        public Nullable<System.DateTime> DataHoraUltimaEmissaoApolice { get; set; }
        public string CodigoFrequenciaCopiaApolice { get; set; }
        public string DescricaoFrequenciaCopiaApolice { get; set; }
        public Nullable<System.DateTime> DataHoraTermino { get; set; }
        public Nullable<bool> FacturaApenasInformativa { get; set; }
        public string PessoaID { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
