//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterconexoesTratamentoDadosPessoais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InterconexoesTratamentoDadosPessoais()
        {
            this.DadosPessoaisTratadosITDP = new HashSet<DadosPessoaisTratadosITDP>();
            this.ITDPFinalidadeTratamento = new HashSet<ITDPFinalidadeTratamento>();
        }
    
        public string IdInterconexoesTratamentoDadosPessoais { get; set; }
        public string ResponsavelId { get; set; }
        public string TratamentoDadosId { get; set; }
        public string ObjectoInterconexao { get; set; }
        public string CodInterconexoesTratamentoDadosPessoais { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DadosPessoaisTratadosITDP> DadosPessoaisTratadosITDP { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual TratamentoDados TratamentoDados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITDPFinalidadeTratamento> ITDPFinalidadeTratamento { get; set; }
    }
}
