//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensPergunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItensPergunta()
        {
            this.PerguntasPlano = new HashSet<PerguntasPlano>();
            this.RespostaPergunta = new HashSet<RespostaPergunta>();
        }
    
        public string IdItem { get; set; }
        public string CodItem { get; set; }
        public Nullable<int> NumItem { get; set; }
        public double Agravamento { get; set; }
        public string Designacao { get; set; }
        public string PerguntaID { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string SubCategoriaItensID { get; set; }
        public bool IsTaxa { get; set; }
        public string EstadoID { get; set; }
        public string TipoAgravamentoId { get; set; }
        public Nullable<bool> IsRadioButton { get; set; }
        public Nullable<bool> IsTextBox { get; set; }
        public Nullable<bool> IsComboBox { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Perguntas Perguntas { get; set; }
        public virtual SubCategoriaItens SubCategoriaItens { get; set; }
        public virtual TipoAgravamento TipoAgravamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerguntasPlano> PerguntasPlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespostaPergunta> RespostaPergunta { get; set; }
    }
}
