//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicencaModuloUser
    {
        public string IdLicencaModuloUser { get; set; }
        public string LicencaModuloID { get; set; }
    
        public virtual LicencaModulo LicencaModulo { get; set; }
    }
}
