//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalidadeAntena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalidadeAntena()
        {
            this.ModalidadesRCSelecionadas = new HashSet<ModalidadesRCSelecionadas>();
            this.ValoresTipoAntena = new HashSet<ValoresTipoAntena>();
        }
    
        public string IdLocalidadeAntena { get; set; }
        public string Designacao { get; set; }
        public string ModalidadeResponsabilidadeCivilID { get; set; }
        public string CodLocalidadeAntena { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ModalidadesResponsabilidadeCivil ModalidadesResponsabilidadeCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModalidadesRCSelecionadas> ModalidadesRCSelecionadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValoresTipoAntena> ValoresTipoAntena { get; set; }
    }
}
