//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalizacaoInstalacoes
    {
        public string IdLocalizacaoInstalacao { get; set; }
        public string TipoInstalacoesID { get; set; }
        public string EnderecoID { get; set; }
        public string InstalacaoID { get; set; }
        public string CodLocalizacaoInstalacoes { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Instalacoes Instalacoes { get; set; }
        public virtual TipoInstalacoes TipoInstalacoes { get; set; }
    }
}
