//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class MargemVendaSeleccionado
    {
        public string IdMargemVendaSeleccionado { get; set; }
        public Nullable<double> Valor { get; set; }
        public string MargemVendaProdutoID { get; set; }
        public string CotacaoID { get; set; }
        public string PessoaId { get; set; }
        public string ApoliceID { get; set; }
        public string EstadoID { get; set; }
        public string CodMargemVendaSeleccionado { get; set; }
    
        public virtual Apolice Apolice { get; set; }
        public virtual Cotacao Cotacao { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual MargemVendaProduto MargemVendaProduto { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
