//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class NacionalidadePessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NacionalidadePessoa()
        {
            this.NacionalidadePessoaPlano = new HashSet<NacionalidadePessoaPlano>();
        }
    
        public string IdNacionalidadePessoa { get; set; }
        public Nullable<bool> Principal { get; set; }
        public string NacionalidadeID { get; set; }
        public string PessoaID { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string CodNacionalidadePessoa { get; set; }
    
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NacionalidadePessoaPlano> NacionalidadePessoaPlano { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
