//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nota()
        {
            this.ContratoNota = new HashSet<ContratoNota>();
            this.SubscricaoCessaoRetencao = new HashSet<SubscricaoCessaoRetencao>();
        }
    
        public string IdNota { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string PrioridadeId { get; set; }
        public string EstadoId { get; set; }
        public string TipoOperacaoId { get; set; }
        public string CategoriaId { get; set; }
        public string PessoaId { get; set; }
        public string CodNota { get; set; }
    
        public virtual CategoriaTarefa CategoriaTarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoNota> ContratoNota { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Prioridade Prioridade { get; set; }
        public virtual OperacoesPagamento OperacoesPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscricaoCessaoRetencao> SubscricaoCessaoRetencao { get; set; }
    }
}
