//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumeroPessoasAbrangivel
    {
        public string IdNumeroPessoasAbrangivel { get; set; }
        public string FormaContratacaoId { get; set; }
        public string CodNumeroPessoasAbrangivel { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
        public string NumeroPessoasAbrangivel1 { get; set; }
        public Nullable<double> NumeroMinPessoasAbrangidas { get; set; }
        public Nullable<double> NumeroMaxPessoasAbrangidas { get; set; }
        public string Nota { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual FormaContratacao FormaContratacao { get; set; }
    }
}
