//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectivosSeccao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectivosSeccao()
        {
            this.ColaboradoresGoi = new HashSet<ColaboradoresGoi>();
        }
    
        public string IdObjectivosSeccao { get; set; }
        public string SeccaoId { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string ObjectivosSectorId { get; set; }
        public Nullable<double> Ponderacao { get; set; }
        public string PlanoObjectivoComercialId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColaboradoresGoi> ColaboradoresGoi { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ObjectivosSector ObjectivosSector { get; set; }
        public virtual PlanoObjectivoComercial PlanoObjectivoComercial { get; set; }
        public virtual Seccao Seccao { get; set; }
    }
}
