//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Perda = new HashSet<Perda>();
        }
    
        public string IdPaciente { get; set; }
        public string NumeroPaciente { get; set; }
        public Nullable<bool> RecebeuAlta { get; set; }
        public Nullable<System.DateTime> DataFimTratamento { get; set; }
        public string ApoliceID { get; set; }
        public string TipoRelacaoSeguradoID { get; set; }
        public string PessoaID { get; set; }
        public string SinistroId { get; set; }
        public string CaminhoBoletimExame { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string CodPaciente { get; set; }
    
        public virtual Apolice Apolice { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Sinistro Sinistro { get; set; }
        public virtual TipoRelacaoSegurado TipoRelacaoSegurado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perda> Perda { get; set; }
    }
}
