//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamentos
    {
        public string IdPagamento { get; set; }
        public string ReciboId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<double> Valor { get; set; }
        public string MoedaId { get; set; }
        public string EstadoId { get; set; }
        public string TipoDocumentoId { get; set; }
        public string Designacao { get; set; }
        public string FormaPagamentoId { get; set; }
    }
}
