//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Papel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Papel()
        {
            this.ComissaoPlano = new HashSet<ComissaoPlano>();
            this.Comissionamento = new HashSet<Comissionamento>();
            this.CondicaoOperacao = new HashSet<CondicaoOperacao>();
            this.ContactoPessoaParteContrato = new HashSet<ContactoPessoaParteContrato>();
            this.HorarioPapel = new HashSet<HorarioPapel>();
            this.Menu = new HashSet<Menu>();
            this.OperacoesCRUDPessoa = new HashSet<OperacoesCRUDPessoa>();
            this.OperacoesPagamento = new HashSet<OperacoesPagamento>();
            this.PartesContrato = new HashSet<PartesContrato>();
            this.PapelDesconto = new HashSet<PapelDesconto>();
            this.PapelPessoa = new HashSet<PapelPessoa>();
            this.PapelPlano = new HashSet<PapelPlano>();
            this.PapelProdutor = new HashSet<PapelProdutor>();
            this.PapelTipoConta = new HashSet<PapelTipoConta>();
            this.PessoaParteContrato = new HashSet<PessoaParteContrato>();
            this.Tarifa = new HashSet<Tarifa>();
            this.TipoConta = new HashSet<TipoConta>();
            this.TipoContratoPapel = new HashSet<TipoContratoPapel>();
            this.TipoOperacao = new HashSet<TipoOperacao>();
            this.TarefasAgendamento = new HashSet<TarefasAgendamento>();
        }
    
        public string IdPapel { get; set; }
        public string Designacao { get; set; }
        public int NumRegistos { get; set; }
        public string CodPapel { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public bool IsProdutor { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string NaturezaMovimentoId { get; set; }
        public bool Contabiliza { get; set; }
        public string TipoSegmentoId { get; set; }
        public string SubContaId { get; set; }
        public string CodDesignacao { get; set; }
        public string TipoContratacaoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComissaoPlano> ComissaoPlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comissionamento> Comissionamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicaoOperacao> CondicaoOperacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactoPessoaParteContrato> ContactoPessoaParteContrato { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioPapel> HorarioPapel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual NaturezaMovimento NaturezaMovimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacoesCRUDPessoa> OperacoesCRUDPessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacoesPagamento> OperacoesPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartesContrato> PartesContrato { get; set; }
        public virtual PlanoContas PlanoContas { get; set; }
        public virtual TipoContratacao TipoContratacao { get; set; }
        public virtual TipoSegmento TipoSegmento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PapelDesconto> PapelDesconto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PapelPessoa> PapelPessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PapelPlano> PapelPlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PapelProdutor> PapelProdutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PapelTipoConta> PapelTipoConta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaParteContrato> PessoaParteContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarifa> Tarifa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoConta> TipoConta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoContratoPapel> TipoContratoPapel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoOperacao> TipoOperacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefasAgendamento> TarefasAgendamento { get; set; }
    }
}
