//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class PapelModuloFuncionalidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PapelModuloFuncionalidade()
        {
            this.ProcessoFuncionalidade = new HashSet<ProcessoFuncionalidade>();
        }
    
        public string IdPapelModuloFuncionalidade { get; set; }
        public string Designacao { get; set; }
        public string FuncionalidadeId { get; set; }
        public string PapelModuloPessoaId { get; set; }
        public string CodPapelModuloFuncionalidade { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Funcionalidade Funcionalidade { get; set; }
        public virtual PapelModuloPessoa PapelModuloPessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessoFuncionalidade> ProcessoFuncionalidade { get; set; }
    }
}
