//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosPlanoContas
    {
        public string IdParametrosPlanoContas { get; set; }
        public Nullable<bool> ListaEmOrdemAlfabetica { get; set; }
        public Nullable<bool> ObrigaCentroCusto { get; set; }
        public Nullable<bool> PermiteMovimentacaoContablidade { get; set; }
        public Nullable<bool> Inativa { get; set; }
        public Nullable<bool> ImprimeNoRelatorioDeEvolucaoDasContas { get; set; }
        public Nullable<bool> ObrigaSubConta { get; set; }
        public Nullable<bool> ContaEstatisticaMovimento { get; set; }
        public Nullable<bool> AlterarPatrimonioPublico { get; set; }
        public string CodParametrosPlanoContas { get; set; }
        public string PlanoContasId { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual PlanoContas PlanoContas { get; set; }
    }
}
