//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipacaoSinistro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipacaoSinistro()
        {
            this.AssinaturasCondutores = new HashSet<AssinaturasCondutores>();
        }
    
        public string IdParticipacaoSinistro { get; set; }
        public string SinistroId { get; set; }
        public string ParticipanteId { get; set; }
        public string AgenciaId { get; set; }
        public string AssinaturaParticipante { get; set; }
        public string AssinaturaTomador { get; set; }
        public string CodParticipacaoSinistro { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string ClassificacaoParticipanteId { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssinaturasCondutores> AssinaturasCondutores { get; set; }
        public virtual ClassificacaoParticipanteSinistro ClassificacaoParticipanteSinistro { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Sinistro Sinistro { get; set; }
    }
}
