//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passageiros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passageiros()
        {
            this.InqueritoPassageiros = new HashSet<InqueritoPassageiros>();
        }
    
        public string IdPassageiros { get; set; }
        public string PessoaId { get; set; }
        public string AutomovelId { get; set; }
        public string SistemaSegurancaId { get; set; }
        public string PosicaoEmQueViajava { get; set; }
        public string DanosCorporais { get; set; }
        public string CodPassageiros { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        public virtual Automovel Automovel { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InqueritoPassageiros> InqueritoPassageiros { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual SistemaSeguranca SistemaSeguranca { get; set; }
    }
}
