//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perguntas()
        {
            this.ItensPergunta = new HashSet<ItensPergunta>();
            this.Perguntas1 = new HashSet<Perguntas>();
            this.QuestionarioTipoLesao = new HashSet<QuestionarioTipoLesao>();
            this.RespostaPergunta = new HashSet<RespostaPergunta>();
        }
    
        public string IdPergunta { get; set; }
        public Nullable<int> NumPergunta { get; set; }
        public string Pergunta { get; set; }
        public string TipoQuestionarioID { get; set; }
        public string LinhaProdutoID { get; set; }
        public Nullable<bool> IsRadioButton { get; set; }
        public Nullable<bool> IsTextBox { get; set; }
        public Nullable<bool> IsCheckBox { get; set; }
        public Nullable<bool> IsComboBox { get; set; }
        public Nullable<bool> IsNumber { get; set; }
        public string CodPerguntas { get; set; }
        public Nullable<bool> IsDatePicker { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string Legenda { get; set; }
        public double Agravamento { get; set; }
        public string PerguntaMaeID { get; set; }
        public bool IsTaxa { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string ModalidadeSeguroId { get; set; }
        public string Nota { get; set; }
        public string Sourc { get; set; }
        public string PlanoProdutoId { get; set; }
        public string TiposPerguntaId { get; set; }
        public string ClassificacaoPerguntasId { get; set; }
        public string CategoriasPerguntaId { get; set; }
    
        public virtual CategoriasPergunta CategoriasPergunta { get; set; }
        public virtual ClassificacaoPerguntas ClassificacaoPerguntas { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensPergunta> ItensPergunta { get; set; }
        public virtual LinhaProduto LinhaProduto { get; set; }
        public virtual ModalidadeSeguro ModalidadeSeguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perguntas> Perguntas1 { get; set; }
        public virtual Perguntas Perguntas2 { get; set; }
        public virtual PlanoProduto PlanoProduto { get; set; }
        public virtual TipoQuestionario TipoQuestionario { get; set; }
        public virtual TiposPergunta TiposPergunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionarioTipoLesao> QuestionarioTipoLesao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespostaPergunta> RespostaPergunta { get; set; }
    }
}
