//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaProfissao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PessoaProfissao()
        {
            this.LocalTrabalhoPessoa = new HashSet<LocalTrabalhoPessoa>();
        }
    
        public string IdPessoaProfissao { get; set; }
        public string EnderecoEmpresaID { get; set; }
        public string PessoaId { get; set; }
        public string ProfissaoID { get; set; }
        public string FormaEntregaID { get; set; }
        public string ContactoEmpresaID { get; set; }
        public string FuncaoID { get; set; }
        public string CategoriaID { get; set; }
        public string NomeEmpresa { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string CodPessoaProfissao { get; set; }
        public string CargoId { get; set; }
        public Nullable<double> SalarioBase { get; set; }
        public Nullable<double> SalarioLiquido { get; set; }
        public Nullable<double> OutroRendimento { get; set; }
        public string SalarioId { get; set; }
        public string CategoriaFuncaoId { get; set; }
        public string EmpresaId { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual CategoriaFuncao CategoriaFuncao { get; set; }
        public virtual CategoriaFuncao CategoriaFuncao1 { get; set; }
        public virtual Contacto Contacto { get; set; }
        public virtual Endereco Endereco { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual FormaEntrega FormaEntrega { get; set; }
        public virtual Funcao Funcao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalTrabalhoPessoa> LocalTrabalhoPessoa { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
        public virtual Profissao Profissao { get; set; }
        public virtual RendimentoPessoa RendimentoPessoa { get; set; }
    }
}
