//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoContas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanoContas()
        {
            this.CentroCusto = new HashSet<CentroCusto>();
            this.CentroResponsabilidade = new HashSet<CentroResponsabilidade>();
            this.ClassificacaoCaixa = new HashSet<ClassificacaoCaixa>();
            this.Cliente = new HashSet<Cliente>();
            this.Cobertura = new HashSet<Cobertura>();
            this.Comite = new HashSet<Comite>();
            this.ContaFinanceira = new HashSet<ContaFinanceira>();
            this.ContasAPagar = new HashSet<ContasAPagar>();
            this.ContratoPrestadorEmpresa = new HashSet<ContratoPrestadorEmpresa>();
            this.Departamento = new HashSet<Departamento>();
            this.Direccao = new HashSet<Direccao>();
            this.Fornecedor = new HashSet<Fornecedor>();
            this.LinhaProduto = new HashSet<LinhaProduto>();
            this.Mapa = new HashSet<Mapa>();
            this.Moeda = new HashSet<Moeda>();
            this.Operacao = new HashSet<Operacao>();
            this.Operacao1 = new HashSet<Operacao>();
            this.OperacoesPagamento = new HashSet<OperacoesPagamento>();
            this.Papel = new HashSet<Papel>();
            this.ParametrosPlanoContas = new HashSet<ParametrosPlanoContas>();
            this.Perda = new HashSet<Perda>();
            this.PlanoComissionamentoProdutor = new HashSet<PlanoComissionamentoProdutor>();
            this.PlanoProduto = new HashSet<PlanoProduto>();
            this.PortfolioProduto = new HashSet<PortfolioProduto>();
            this.Premios = new HashSet<Premios>();
            this.Produto = new HashSet<Produto>();
            this.Recibo = new HashSet<Recibo>();
            this.Seccao = new HashSet<Seccao>();
            this.Sector = new HashSet<Sector>();
            this.SegmentoProduto = new HashSet<SegmentoProduto>();
            this.PlanoContas1 = new HashSet<PlanoContas>();
            this.Tarifa = new HashSet<Tarifa>();
            this.TarifasAutomovel = new HashSet<TarifasAutomovel>();
            this.TarifasDanosProprios = new HashSet<TarifasDanosProprios>();
            this.TarifasPremioAutoAcidentesTrabalho = new HashSet<TarifasPremioAutoAcidentesTrabalho>();
            this.TarifasPremioAutoAT2 = new HashSet<TarifasPremioAutoAT2>();
            this.TarifasResponsabilidadeCivil = new HashSet<TarifasResponsabilidadeCivil>();
            this.TipoComissao = new HashSet<TipoComissao>();
            this.TipoConta = new HashSet<TipoConta>();
            this.TipoOperacao = new HashSet<TipoOperacao>();
            this.TipoOperacao1 = new HashSet<TipoOperacao>();
        }
    
        public string IdSubClasse { get; set; }
        public string NumSubClasse { get; set; }
        public string Designacao { get; set; }
        public string SubClasseContaID { get; set; }
        public string ClasseID { get; set; }
        public string TipoClasseContaID { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<int> Grau { get; set; }
        public string EstadoID { get; set; }
        public Nullable<double> Saldo { get; set; }
        public Nullable<double> SaldoAberturaDebito { get; set; }
        public Nullable<double> SaldoAberturaCredito { get; set; }
        public Nullable<double> SaldoAnterior { get; set; }
        public string ConceitoConta { get; set; }
        public Nullable<double> Valor { get; set; }
        public string Conta { get; set; }
        public string Risco { get; set; }
        public string Auxiliar { get; set; }
        public string CodPlanoContas { get; set; }
        public string CategoriaTipoContaID { get; set; }
        public Nullable<decimal> SaldoEncerramentoCredito { get; set; }
        public Nullable<decimal> SaldoEncerramentoDebito { get; set; }
        public string NumLen { get; set; }
        public string Natureza { get; set; }
        public string Tipo { get; set; }
        public string TipoMovimenntacao { get; set; }
        public string ClasseConta { get; set; }
        public string ActividadeEmpresaId { get; set; }
    
        public virtual ActividadeEmpresa ActividadeEmpresa { get; set; }
        public virtual CategoriaTipoConta CategoriaTipoConta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentroCusto> CentroCusto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentroResponsabilidade> CentroResponsabilidade { get; set; }
        public virtual ClasseConta ClasseConta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassificacaoCaixa> ClassificacaoCaixa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobertura> Cobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comite> Comite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContaFinanceira> ContaFinanceira { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContasAPagar> ContasAPagar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoPrestadorEmpresa> ContratoPrestadorEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamento> Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccao> Direccao { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornecedor> Fornecedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinhaProduto> LinhaProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mapa> Mapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moeda> Moeda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacao> Operacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacao> Operacao1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacoesPagamento> OperacoesPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Papel> Papel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParametrosPlanoContas> ParametrosPlanoContas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perda> Perda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanoComissionamentoProdutor> PlanoComissionamentoProdutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanoProduto> PlanoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortfolioProduto> PortfolioProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Premios> Premios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produto> Produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recibo> Recibo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seccao> Seccao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sector> Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentoProduto> SegmentoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanoContas> PlanoContas1 { get; set; }
        public virtual PlanoContas PlanoContas2 { get; set; }
        public virtual TipoClasseConta TipoClasseConta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarifa> Tarifa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifasAutomovel> TarifasAutomovel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifasDanosProprios> TarifasDanosProprios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifasPremioAutoAcidentesTrabalho> TarifasPremioAutoAcidentesTrabalho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifasPremioAutoAT2> TarifasPremioAutoAT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifasResponsabilidadeCivil> TarifasResponsabilidadeCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoComissao> TipoComissao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoConta> TipoConta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoOperacao> TipoOperacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoOperacao> TipoOperacao1 { get; set; }
    }
}
