//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecosMedicamentos
    {
        public string IdPrecarioMedicamentos { get; set; }
        public Nullable<int> Unidade { get; set; }
        public Nullable<int> Minimo { get; set; }
        public string IdPessoa { get; set; }
        public string IdMedicamento { get; set; }
        public string Valor { get; set; }
        public string IdMoeda { get; set; }
        public string PvPaOA { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string CodPrecosMedicamentos { get; set; }
    
        public virtual Medicamentos Medicamentos { get; set; }
        public virtual Moeda Moeda { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
