//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestacoesFraccionamento
    {
        public string IdPrestacao { get; set; }
        public Nullable<int> NumPrestacao { get; set; }
        public double Percentagem { get; set; }
        public string Designacao { get; set; }
        public string CodPrestacoesFraccionamento { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public bool IsTaxa { get; set; }
        public string EstadoID { get; set; }
        public string FraccionamentoProdutoId { get; set; }
        public Nullable<double> PremioMinimoAnual { get; set; }
    
        public virtual Estado Estado { get; set; }
    }
}
