//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoVendas
    {
        public string idProdutoVendas { get; set; }
        public string CodProdutoVendas { get; set; }
        public string estadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string MovimentoID { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Movimento Movimento { get; set; }
    }
}
