//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projecto()
        {
            this.ActividadeProjecto = new HashSet<ActividadeProjecto>();
            this.CustoProjecto = new HashSet<CustoProjecto>();
            this.DocumentoProjecto = new HashSet<DocumentoProjecto>();
            this.Entregaveis = new HashSet<Entregaveis>();
            this.HorasActividades = new HashSet<HorasActividades>();
            this.Incidentes = new HashSet<Incidentes>();
            this.ProjectoGestores = new HashSet<ProjectoGestores>();
            this.ProjectoRiscos = new HashSet<ProjectoRiscos>();
            this.RecursoProjecto = new HashSet<RecursoProjecto>();
            this.Reunioes = new HashSet<Reunioes>();
        }
    
        public string IdProjecto { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Orcamento { get; set; }
        public string CodProjecto { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataTermino { get; set; }
        public string SituacaoId { get; set; }
        public string PortfolioId { get; set; }
        public string AmbitoProjecto { get; set; }
        public string ObjectivoProjecto { get; set; }
        public string PropostaId { get; set; }
        public string EquipeId { get; set; }
        public string TipoProjectoId { get; set; }
        public Nullable<System.DateTime> DataInicioPrevisto { get; set; }
        public Nullable<System.DateTime> DataConclusaoPrevista { get; set; }
        public Nullable<System.DateTime> DataInicioProjecto { get; set; }
        public Nullable<System.DateTime> DataConclusaoProjecto { get; set; }
        public string FornecedorId { get; set; }
        public string MetodologiaId { get; set; }
        public string RiscoId { get; set; }
        public string ProgramaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadeProjecto> ActividadeProjecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustoProjecto> CustoProjecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoProjecto> DocumentoProjecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entregaveis> Entregaveis { get; set; }
        public virtual Equipe Equipe { get; set; }
        public virtual Fornecedores Fornecedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorasActividades> HorasActividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidentes> Incidentes { get; set; }
        public virtual Metodologias Metodologias { get; set; }
        public virtual Portfolio Portfolio { get; set; }
        public virtual Programas Programas { get; set; }
        public virtual PropostasProjecto PropostasProjecto { get; set; }
        public virtual Situacao Situacao { get; set; }
        public virtual TipoProjecto TipoProjecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectoGestores> ProjectoGestores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectoRiscos> ProjectoRiscos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecursoProjecto> RecursoProjecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reunioes> Reunioes { get; set; }
    }
}
