//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropostasProjecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropostasProjecto()
        {
            this.Projecto = new HashSet<Projecto>();
        }
    
        public string IdPropostasProjecto { get; set; }
        public string OportunidadeProjectoId { get; set; }
        public string Designacao { get; set; }
        public string AmbitoProposta { get; set; }
        public string Observacoes { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string UnidadeMonetaria { get; set; }
        public Nullable<System.DateTime> Prazo { get; set; }
        public string MetodoId { get; set; }
        public string FornecedoresID { get; set; }
        public string CodOportunidadesFornecedores { get; set; }
        public string Estadoid { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string PortfolioId { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual Fornecedores Fornecedores { get; set; }
        public virtual Metodologias Metodologias { get; set; }
        public virtual OportunidadeProjecto OportunidadeProjecto { get; set; }
        public virtual Portfolio Portfolio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projecto> Projecto { get; set; }
    }
}
