//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reclamacao()
        {
            this.ContratoPrestadorEmpresa = new HashSet<ContratoPrestadorEmpresa>();
        }
    
        public string IdReclamacao { get; set; }
        public string Designacao { get; set; }
        public Nullable<System.DateTime> DataPreenchimentoFormulario { get; set; }
        public Nullable<System.DateTime> DataHoraEfectividadeEstado { get; set; }
        public Nullable<bool> CompletamenteResolvido { get; set; }
        public string CodigoResponsabilidadeID { get; set; }
        public string RazaoPeloRecuso { get; set; }
        public string CausadorDoIncidenteID { get; set; }
        public string DescricaoCulpadoIncidente { get; set; }
        public Nullable<bool> ApoliceCancelada { get; set; }
        public Nullable<bool> ReclamadorAlugouCarro { get; set; }
        public Nullable<bool> SeguradorAceitaCustoAluguel { get; set; }
        public Nullable<bool> ApoliceEstadoRenovacao { get; set; }
        public string ResponsavelPelaReclamacaoID { get; set; }
        public string ReclamadorID { get; set; }
        public string PessoaRelacionadaID { get; set; }
        public string ApoliceID { get; set; }
        public string ClassificacaoReclamacaoID { get; set; }
        public string EstadoID { get; set; }
        public string PerdaID { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string CodReclamacao { get; set; }
    
        public virtual Apolice Apolice { get; set; }
        public virtual ClassificacaoReclamacao ClassificacaoReclamacao { get; set; }
        public virtual CodigoResponsabilidade CodigoResponsabilidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoPrestadorEmpresa> ContratoPrestadorEmpresa { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Perda Perda { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
        public virtual Pessoa Pessoa2 { get; set; }
        public virtual Pessoa Pessoa3 { get; set; }
    }
}
