//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reembolso
    {
        public string IdReembolso { get; set; }
        public string PrestadorId { get; set; }
        public string SeguradoId { get; set; }
        public string TipoDespesaId { get; set; }
        public Nullable<System.DateTime> DataRealizacao { get; set; }
        public string NumeroFactura { get; set; }
        public double ValorFactura { get; set; }
        public string DescricaoDiagnostico { get; set; }
        public string ReciboOriginal { get; set; }
        public string InformacaoAdicional { get; set; }
        public string Assinatura { get; set; }
        public string CodReembolso { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Segurado Segurado { get; set; }
        public virtual TipoDespesa TipoDespesa { get; set; }
    }
}
