//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReembolsoTratamentoDentario
    {
        public string IdReembolsoTratamentoDentario { get; set; }
        public string CodReembolsoTratamentoDentario { get; set; }
        public string PessoaSegura { get; set; }
        public string GrauParentesco { get; set; }
        public string Estomatologista { get; set; }
        public string SinistroId { get; set; }
        public string RazaoColocacao { get; set; }
        public Nullable<System.DateTime> DataColocacaoAnterior { get; set; }
        public string DescricaoTratamentoDentario { get; set; }
        public Nullable<System.DateTime> DataActualizacao { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public string EstadoId { get; set; }
    
        public virtual DescricaoTratamentoDentario DescricaoTratamentoDentario1 { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual GrauParentesco GrauParentesco1 { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Sinistro Sinistro { get; set; }
    }
}
