//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatorioPolicia
    {
        public string IdRelatorioPolicia { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public string CaminhoFicheiro { get; set; }
        public string SinistroID { get; set; }
        public string TipoAutoridadeID { get; set; }
        public string NomeAgente { get; set; }
        public string NumIdentAgente { get; set; }
        public string TelemovelAgente { get; set; }
        public string DescricaoPormenorizadaAgente { get; set; }
        public string NumProcessoPolicia { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Sinistro Sinistro { get; set; }
        public virtual TipoAutoridade TipoAutoridade { get; set; }
    }
}
