//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespostaPergunta
    {
        public string IdRespostaQuestionario { get; set; }
        public string PerguntaID { get; set; }
        public string Detalhes { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string ItemPerguntaId { get; set; }
        public string AutomovelId { get; set; }
        public string CotacaoId { get; set; }
        public string Resposta { get; set; }
        public string QuestionarioID { get; set; }
        public string InqueritoCondutorId { get; set; }
    
        public virtual Automovel Automovel { get; set; }
        public virtual Cotacao Cotacao { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual InqueritoMotorista InqueritoMotorista { get; set; }
        public virtual ItensPergunta ItensPergunta { get; set; }
        public virtual Perguntas Perguntas { get; set; }
        public virtual Questionario Questionario { get; set; }
    }
}
