//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saldo
    {
        public string IdSaldo { get; set; }
        public string CodSaldo { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataActualizacao { get; set; }
        public string ContaFinanceiraId { get; set; }
        public Nullable<double> SaldoConta { get; set; }
        public Nullable<double> SaldoDisponivel { get; set; }
        public Nullable<double> SaldoContabilistico { get; set; }
        public Nullable<double> SaldoCativo { get; set; }
        public string EstadoId { get; set; }
    
        public virtual ContaFinanceira ContaFinanceira { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
