//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sector()
        {
            this.CentroCusto = new HashSet<CentroCusto>();
            this.CentroResponsabilidade = new HashSet<CentroResponsabilidade>();
            this.EstatutoOrganicoSector = new HashSet<EstatutoOrganicoSector>();
            this.Funcionario = new HashSet<Funcionario>();
            this.ObjectivosSector = new HashSet<ObjectivosSector>();
            this.OperacoesCRUDPessoa = new HashSet<OperacoesCRUDPessoa>();
            this.ProcessosSector = new HashSet<ProcessosSector>();
            this.Seccao = new HashSet<Seccao>();
            this.ServicosSector = new HashSet<ServicosSector>();
            this.TarefasSector = new HashSet<TarefasSector>();
        }
    
        public string IdSector { get; set; }
        public string NomeSector { get; set; }
        public string ContactoID { get; set; }
        public string CodSector { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string SubContaID { get; set; }
        public bool Contabiliza { get; set; }
        public string DepartamentoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentroCusto> CentroCusto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentroResponsabilidade> CentroResponsabilidade { get; set; }
        public virtual Contacto Contacto { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstatutoOrganicoSector> EstatutoOrganicoSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionario> Funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectivosSector> ObjectivosSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacoesCRUDPessoa> OperacoesCRUDPessoa { get; set; }
        public virtual PlanoContas PlanoContas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessosSector> ProcessosSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seccao> Seccao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicosSector> ServicosSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefasSector> TarefasSector { get; set; }
    }
}
