//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectorAtividadeEconomica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SectorAtividadeEconomica()
        {
            this.CAE = new HashSet<CAE>();
            this.DescontoSectorActividade = new HashSet<DescontoSectorActividade>();
            this.SectorActividadesProdutor = new HashSet<SectorActividadesProdutor>();
            this.SectorAtividadeEconomicaContrato = new HashSet<SectorAtividadeEconomicaContrato>();
        }
    
        public string IdSectorAtividadeEconomica { get; set; }
        public string CodSectorAtividadeEconomica { get; set; }
        public string Designacao { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string TipoSociedadeId { get; set; }
        public string Seccao { get; set; }
        public string SubSeccao { get; set; }
        public string DesignacaoSubSeccao { get; set; }
        public string GrupoCaeId { get; set; }
        public string TipoRegimeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAE> CAE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoSectorActividade> DescontoSectorActividade { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual GrupoCae GrupoCae { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectorActividadesProdutor> SectorActividadesProdutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectorAtividadeEconomicaContrato> SectorAtividadeEconomicaContrato { get; set; }
        public virtual TipoRegime TipoRegime { get; set; }
        public virtual TipoSociedade TipoSociedade { get; set; }
    }
}
