//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemaAquecimento
    {
        public string IdSistemaAquecimento { get; set; }
        public Nullable<bool> TermostaticamenteControlado { get; set; }
        public string AreaAquecida { get; set; }
        public Nullable<System.DateTime> DataHoraInstalacao { get; set; }
        public Nullable<bool> Certificado { get; set; }
        public string MetodoSistemaAquecimentoId { get; set; }
        public string CombustivelID { get; set; }
        public string ConstrucaoID { get; set; }
        public string CodSistemaAquecimento { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
    
        public virtual Combustivel Combustivel { get; set; }
        public virtual Construcao Construcao { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual MetodoSistemaAquecimento MetodoSistemaAquecimento { get; set; }
    }
}
