//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public string IdSlide { get; set; }
        public string Descricao { get; set; }
        public string Designacao { get; set; }
        public string CaminhoFoto { get; set; }
        public string LinkProduto { get; set; }
        public string CodSlide { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public Nullable<bool> IsEmpresa { get; set; }
        public Nullable<bool> IsSite { get; set; }
        public Nullable<bool> IsParticular { get; set; }
    
        public virtual Estado Estado { get; set; }
    }
}
