//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubFormaResseguro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubFormaResseguro()
        {
            this.CoberturaResseguro = new HashSet<CoberturaResseguro>();
            this.SubFormaResseguro1 = new HashSet<SubFormaResseguro>();
        }
    
        public string IdSubFormaResseguro { get; set; }
        public string Designacao { get; set; }
        public string FormaResseguroId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string CodSubFormaResseguro { get; set; }
        public string EstadoId { get; set; }
        public string SubFormaResseguroId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoberturaResseguro> CoberturaResseguro { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual FormaResseguro FormaResseguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubFormaResseguro> SubFormaResseguro1 { get; set; }
        public virtual SubFormaResseguro SubFormaResseguro2 { get; set; }
    }
}
