//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarefa()
        {
            this.ContratoTarefa = new HashSet<ContratoTarefa>();
            this.PessoaTarefa = new HashSet<PessoaTarefa>();
            this.RiscosTarefa = new HashSet<RiscosTarefa>();
            this.SubscricaoCessaoRetencao = new HashSet<SubscricaoCessaoRetencao>();
            this.SubTarefa = new HashSet<SubTarefa>();
            this.TarefaPlano = new HashSet<TarefaPlano>();
            this.TarefasActividade = new HashSet<TarefasActividade>();
            this.TarefasDepartamento = new HashSet<TarefasDepartamento>();
            this.TarefasDireccao = new HashSet<TarefasDireccao>();
            this.TarefasPerfil = new HashSet<TarefasPerfil>();
            this.TarefasSector = new HashSet<TarefasSector>();
            this.TarefasSeccao = new HashSet<TarefasSeccao>();
            this.TipoContratoTarefa = new HashSet<TipoContratoTarefa>();
        }
    
        public string IdTarefa { get; set; }
        public string PCFid { get; set; }
        public string HierarquiaID { get; set; }
        public string Nome { get; set; }
        public string MetricaDisponivel { get; set; }
        public Nullable<int> IndiceDiferenca { get; set; }
        public string DetalhesMudanca { get; set; }
        public string CodTarefa { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string NivelRiscoID { get; set; }
        public string EstadoId { get; set; }
        public string PrioridadeID { get; set; }
        public string UltModificacaoPorID { get; set; }
        public string SituacaoId { get; set; }
        public string ProjectoId { get; set; }
        public string CategoriaTarefaID { get; set; }
    
        public virtual CategoriaTarefa CategoriaTarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoTarefa> ContratoTarefa { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual NivelRisco NivelRisco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaTarefa> PessoaTarefa { get; set; }
        public virtual Prioridade Prioridade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiscosTarefa> RiscosTarefa { get; set; }
        public virtual Situacao Situacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscricaoCessaoRetencao> SubscricaoCessaoRetencao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubTarefa> SubTarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaPlano> TarefaPlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefasActividade> TarefasActividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefasDepartamento> TarefasDepartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefasDireccao> TarefasDireccao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefasPerfil> TarefasPerfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefasSector> TarefasSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefasSeccao> TarefasSeccao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoContratoTarefa> TipoContratoTarefa { get; set; }
    }
}
