//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarefasActividade
    {
        public string IdTarefasActividade { get; set; }
        public string ActividadeID { get; set; }
        public string TarefaID { get; set; }
        public string SubTarefaID { get; set; }
    
        public virtual Actividade Actividade { get; set; }
        public virtual SubTarefa SubTarefa { get; set; }
        public virtual Tarefa Tarefa { get; set; }
    }
}
