//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxaDanosProprio
    {
        public string IdAgravamentoDanosProprio { get; set; }
        public Nullable<double> Taxa { get; set; }
        public string CategoriaId { get; set; }
        public string ClassificacaoAutomovelId { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ClassificacaoAutomovel ClassificacaoAutomovel { get; set; }
    }
}
