//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termos
    {
        public string IdTermos { get; set; }
        public string Termo { get; set; }
        public string Descricao { get; set; }
        public string UrlImagem { get; set; }
        public string TipoTermoId { get; set; }
        public string TitulosId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string CodTermos { get; set; }
        public string EstadoId { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual TipoTermos TipoTermos { get; set; }
        public virtual Titulos Titulos { get; set; }
    }
}
