//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public string IdCobertura { get; set; }
        public string DescricaoCobertura { get; set; }
        public Nullable<System.DateTime> DataEfectividadeCobertura { get; set; }
        public Nullable<System.DateTime> DataTerminoCobertura { get; set; }
        public Nullable<double> ValorMin { get; set; }
        public Nullable<double> ValorMax { get; set; }
        public Nullable<double> CooPagamentoMin { get; set; }
        public Nullable<double> CooPagamentoMax { get; set; }
        public double TaxaCooPagamento { get; set; }
        public Nullable<bool> CoberturaAdicional { get; set; }
        public Nullable<bool> CoberturaRenovavel { get; set; }
        public Nullable<bool> CustoCoberturaQualificado { get; set; }
        public Nullable<int> NumReivindicacoesPermitidas { get; set; }
        public Nullable<bool> CoberturaSujeitaCoSeguro { get; set; }
        public Nullable<bool> CoberturaDeveEstarRenovacao { get; set; }
        public Nullable<bool> CoberturaSolicitada { get; set; }
        public Nullable<bool> ForneceValorResgateEmDinheiro { get; set; }
        public Nullable<bool> SubContratentesCobertos { get; set; }
        public string EstadoID { get; set; }
        public string TipoCoberturaID { get; set; }
        public string PlanoProdutoID { get; set; }
        public Nullable<double> PercentagemDentroRede { get; set; }
        public Nullable<double> PercentagemForaRede { get; set; }
        public string MoedaId { get; set; }
        public string CodCoberturaProduto { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string Obs { get; set; }
        public Nullable<double> LimiteIndemnizacao { get; set; }
        public bool IsTaxa { get; set; }
        public string SubContaID { get; set; }
        public string NaturezaMovimentoID { get; set; }
        public bool Contabiliza { get; set; }
        public Nullable<bool> IsPadrao { get; set; }
        public string LinhaProdutoID { get; set; }
        public string CodDesconto { get; set; }
        public string FranquiaId { get; set; }
        public Nullable<double> Capital { get; set; }
        public Nullable<double> PercentagemMinimaForaRede { get; set; }
        public Nullable<double> PercentagemMaximaForaRede { get; set; }
    }
}
