//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCobertura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoCobertura()
        {
            this.AgravamentoLimiteComparticipacao = new HashSet<AgravamentoLimiteComparticipacao>();
            this.Cobertura = new HashSet<Cobertura>();
            this.CoberturaPlano = new HashSet<CoberturaPlano>();
            this.CoeficientePremioAdesao = new HashSet<CoeficientePremioAdesao>();
            this.CoeficientePremioAdesao1 = new HashSet<CoeficientePremioAdesao>();
            this.CoeficientePremioDoencasPreExistentes = new HashSet<CoeficientePremioDoencasPreExistentes>();
            this.CoeficientePremioDoencasPreExistentes1 = new HashSet<CoeficientePremioDoencasPreExistentes>();
            this.CoeficientePremioLimiteIndemnizacao = new HashSet<CoeficientePremioLimiteIndemnizacao>();
            this.CoeficientePremioLimiteIndemnizacao1 = new HashSet<CoeficientePremioLimiteIndemnizacao>();
            this.CoeficientePremioPessoas = new HashSet<CoeficientePremioPessoas>();
            this.DescontoFranquia = new HashSet<DescontoFranquia>();
            this.DocumentosObrigatorioProduto = new HashSet<DocumentosObrigatorioProduto>();
            this.GarantiasContratadas = new HashSet<GarantiasContratadas>();
            this.LimitesAceitacao = new HashSet<LimitesAceitacao>();
            this.LocaisCobertura = new HashSet<LocaisCobertura>();
            this.NivelRiscoCobertura = new HashSet<NivelRiscoCobertura>();
            this.RiscosExcluidos = new HashSet<RiscosExcluidos>();
            this.SegmentoTipoCobertura = new HashSet<SegmentoTipoCobertura>();
            this.TermoResponsabilidade = new HashSet<TermoResponsabilidade>();
        }
    
        public string IdTipo { get; set; }
        public string NomeCobertura { get; set; }
        public string ProdutoID { get; set; }
        public string CaminhoIcone { get; set; }
        public string CodTipoCobertura { get; set; }
        public Nullable<int> DiasPeriodoCarencia { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string Obs { get; set; }
        public string LinhaProdutoID { get; set; }
        public string EstadoID { get; set; }
        public string SubContaID { get; set; }
        public string NaturezaMovimentoID { get; set; }
        public bool Contabiliza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgravamentoLimiteComparticipacao> AgravamentoLimiteComparticipacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobertura> Cobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoberturaPlano> CoberturaPlano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficientePremioAdesao> CoeficientePremioAdesao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficientePremioAdesao> CoeficientePremioAdesao1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficientePremioDoencasPreExistentes> CoeficientePremioDoencasPreExistentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficientePremioDoencasPreExistentes> CoeficientePremioDoencasPreExistentes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficientePremioLimiteIndemnizacao> CoeficientePremioLimiteIndemnizacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficientePremioLimiteIndemnizacao> CoeficientePremioLimiteIndemnizacao1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoeficientePremioPessoas> CoeficientePremioPessoas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescontoFranquia> DescontoFranquia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosObrigatorioProduto> DocumentosObrigatorioProduto { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GarantiasContratadas> GarantiasContratadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LimitesAceitacao> LimitesAceitacao { get; set; }
        public virtual LinhaProduto LinhaProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocaisCobertura> LocaisCobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NivelRiscoCobertura> NivelRiscoCobertura { get; set; }
        public virtual Produto Produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiscosExcluidos> RiscosExcluidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentoTipoCobertura> SegmentoTipoCobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TermoResponsabilidade> TermoResponsabilidade { get; set; }
    }
}
