//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoComissionamentoResseguro
    {
        public string IdTipoComissionamentoResseguro { get; set; }
        public string ComissionamentoId { get; set; }
        public string CodTipoComissionamentoResseguro { get; set; }
        public string ContratoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
        public string Designacao { get; set; }
    
        public virtual Comissionamento Comissionamento { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
