//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoOperacaoProcesso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoOperacaoProcesso()
        {
            this.TipoOperacaoProcessoLimiteCompetencia = new HashSet<TipoOperacaoProcessoLimiteCompetencia>();
        }
    
        public string IdTipoOperacaoProcesso { get; set; }
        public string TipoOperacaoId { get; set; }
        public string CodTipoOperacaoProcesso { get; set; }
        public string ProcessoFuncionalidadeId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ProcessoFuncionalidade ProcessoFuncionalidade { get; set; }
        public virtual TipoOperacao TipoOperacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoOperacaoProcessoLimiteCompetencia> TipoOperacaoProcessoLimiteCompetencia { get; set; }
    }
}
