//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumentoFormaPagamento
    {
        public string IdTipoDocumentoFormaPagamento { get; set; }
        public string TipoDocumentoId { get; set; }
        public string FormaPagamentoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        public virtual FormaPagamento FormaPagamento { get; set; }
        public virtual TipoDocumentos TipoDocumentos { get; set; }
    }
}
