//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposContratosResseguroInformacoesTiposContratosResseguro
    {
        public string IdTiposContratosResseguroInformacoesTiposContratosResseguro { get; set; }
        public string TiposContratosResseguroId { get; set; }
        public string InformacoesTiposContratosResseguroId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string CodTiposContratosResseguroInformacoesTiposContratosResseguro { get; set; }
    
        public virtual SubFormaResseguroInformacao SubFormaResseguroInformacao { get; set; }
        public virtual TiposContratosResseguro TiposContratosResseguro { get; set; }
    }
}
