//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titularidade
    {
        public string IdTitularidade { get; set; }
        public string PessoaId { get; set; }
        public Nullable<bool> Principal { get; set; }
        public string ContaFinanceiraId { get; set; }
        public string CaminhoFicheiro { get; set; }
    
        public virtual ContaFinanceira ContaFinanceira { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
