//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class TratamentoDados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TratamentoDados()
        {
            this.CanalTratamentoDados = new HashSet<CanalTratamentoDados>();
            this.ComunicacaoDadosTerceiros = new HashSet<ComunicacaoDadosTerceiros>();
            this.CTDPTratamentoDados = new HashSet<CTDPTratamentoDados>();
            this.DadosPessoaisTratadosTratamentoDados = new HashSet<DadosPessoaisTratadosTratamentoDados>();
            this.ExercicioDireitoAcessoTratamentoDados = new HashSet<ExercicioDireitoAcessoTratamentoDados>();
            this.InterconexoesTratamentoDadosPessoais = new HashSet<InterconexoesTratamentoDadosPessoais>();
            this.ProcessamentoInformacao = new HashSet<ProcessamentoInformacao>();
            this.TratamentoDadosFinalidadesTratamento = new HashSet<TratamentoDadosFinalidadesTratamento>();
            this.TratamentoDadosMedidasSeguranca = new HashSet<TratamentoDadosMedidasSeguranca>();
        }
    
        public string IdTratamentoDados { get; set; }
        public string ResponsavelId { get; set; }
        public string RepresentanteId { get; set; }
        public string PrazoConservacaoDadosPessoaisId { get; set; }
        public string CodTratamentoDados { get; set; }
        public string EstadoId { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanalTratamentoDados> CanalTratamentoDados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicacaoDadosTerceiros> ComunicacaoDadosTerceiros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDPTratamentoDados> CTDPTratamentoDados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DadosPessoaisTratadosTratamentoDados> DadosPessoaisTratadosTratamentoDados { get; set; }
        public virtual DirectorDireccao DirectorDireccao { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExercicioDireitoAcessoTratamentoDados> ExercicioDireitoAcessoTratamentoDados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterconexoesTratamentoDadosPessoais> InterconexoesTratamentoDadosPessoais { get; set; }
        public virtual PrazoConservacaoDadosPessoais PrazoConservacaoDadosPessoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessamentoInformacao> ProcessamentoInformacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TratamentoDadosFinalidadesTratamento> TratamentoDadosFinalidadesTratamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TratamentoDadosMedidasSeguranca> TratamentoDadosMedidasSeguranca { get; set; }
    }
}
