//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Warning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorCativo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValorCativo()
        {
            this.ContaFinanceira = new HashSet<ContaFinanceira>();
        }
    
        public string IdValorCativo { get; set; }
        public string CodValorCativo { get; set; }
        public string ContaId { get; set; }
        public string MoedaId { get; set; }
        public Nullable<System.DateTime> DataCavito { get; set; }
        public Nullable<int> PrazoCativo { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string EstadoId { get; set; }
        public string TipoJustificativoCativoId { get; set; }
        public string TipoContaId { get; set; }
        public Nullable<double> Valor { get; set; }
        public string CativadoPorId { get; set; }
        public string DescativadoPorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContaFinanceira> ContaFinanceira { get; set; }
        public virtual ContaFinanceira ContaFinanceira1 { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Funcionario Funcionario1 { get; set; }
        public virtual Moeda Moeda { get; set; }
        public virtual TipoConta TipoConta { get; set; }
        public virtual TipoJustificativoCativo TipoJustificativoCativo { get; set; }
    }
}
